[package]
name = "raito"
version = "0.1.0"
edition = "2023_11"

[scripts]
get_block= "./scripts/data/get_block.sh"
get_blocks= "./scripts/data/get_blocks.sh"

[dependencies]

[dev-dependencies]
cairo_test = "2.7.0"